name: Update README with WakaTime Stats

on:
  schedule:
    - cron: "0 0 * * *"  # Runs at 12:00 UTC every day
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Fetch WakaTime stats
        run: |
          curl -s "https://wakatime.com/api/v1/users/current/stats/last_7_days?api_key=${{ secrets.WAKATIME_API_KEY }}" > wakatime.json

      - name: Calculate total coding hours
        run: |
          total_seconds=$(jq -r '.data.total_seconds' wakatime.json)
          total_hours=$(awk "BEGIN {print int($total_seconds / 3600)}")

      - name: Generate WakaTime Stats
        run: |
          top_languages=$(jq -r '.data.languages | sort_by(.percent) | reverse | limit(5; .[]) | "- \(.name): \(.percent)% (\(.text))"' wakatime.json)
          echo "## 📊 WakaTime Stats\n\n### Top 5 Languages:\n\n$top_languages\n\n### Total Coding Activity: $total_hours hours" > WAKATIME.md

      - name: Update README
        run: |
          awk 'NR==FNR{a[++d]=$0;next}/<!--START_SECTION:waka-->/{print;print "<!--WAKATIME_STATS_START-->";for(i=1;i<=d;i++)print a[i];print "<!--WAKATIME_STATS_END-->";next}1' WAKATIME.md README.md > README_tmp.md
          mv README_tmp.md README.md

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add README.md WAKATIME.md wakatime.json
          git commit -m 'Update README with WakaTime stats'
          git push

