name: Update README with WakaTime Stats

on:
  schedule:
    - cron: "0 12 * * *"  # Runs at 12:00 UTC every day
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Fetch WakaTime stats
        id: wakatime
        run: |
          curl -s "https://wakatime.com/api/v1/users/current/stats/last_7_days?api_key=${{ secrets.WAKATIME_API_KEY }}" > wakatime.json

      - name: Generate WakaTime Stats
        run: |
          total_time=$(jq -r '.data.total_seconds' wakatime.json)
          languages=$(jq -r '.data.languages | sort_by(.percent) | reverse | limit(5; .[]) | "\(.name): \(.percent)% (\(.text))"' wakatime.json)
          echo "## 📊 WakaTime Stats\n\n### Top 5 Languages:\n\n$languages\n\n### Total Coding Activity: $(($total_time / 3600)) hours" > WAKATIME.md

      - name: Update README
        run: |
          awk 'NR==FNR{a[++d]=$0;next}/<!--START_SECTION:waka-->/{print;print "<!--WAKATIME_STATS_START-->";for(i=1;i<=d;i++)print a[i];print "<!--WAKATIME_STATS_END-->";next}1' WAKATIME.md README.md > README_tmp.md
          mv README_tmp.md README.md

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add README.md WAKATIME.md wakatime.json
          git commit -m 'Update README with WakaTime stats' || echo "No changes to commit"

      - name: Pull latest changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git remote set-url origin https://${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git
          git pull origin main --rebase

      - name: Push changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git push origin main
